FROM registry.access.redhat.com/ubi8/openjdk-21-runtime:1.20

ENV LANGUAGE='en_US:en'

COPY target/*.jar /deployments/

EXPOSE 8080
USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/embitious-1.0.0-SNAPSHOT.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
