# Embitious Vector Embedding Service Configuration

# HTTP Configurations
quarkus.http.port=8080
quarkus.http.root-path=/

# Artemis JMS Configurations
# Connection URL for the external message broker
quarkus.artemis.url=tcp://localhost:61616
# Connection credentials (optional/default)
quarkus.artemis.username=artemis
quarkus.artemis.password=artemis

# Custom Embedding configurations
# Model to use. By default we use the standard sentence-transformers all-MiniLM-L6-v2
embitious.embedding.model-name=sentence-transformers/all-MiniLM-L6-v2
# Offline execution: when true, forces DJL to run locally using native PyTorch binaries and cached models without any outbound API requests
embitious.embedding.offline=false

# JMS queue/topic configurations
embitious.jms.request-queue=embeddings.requests
embitious.jms.response-queue=embeddings.responses
